
import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export function useLanguage() {
    return useContext(LanguageContext)
}

export const LANGUAGES = {
    en: { name: 'English', dir: 'ltr' },
    hi: { name: 'Hindi', dir: 'ltr' },
    pa: { name: 'Punjabi', dir: 'ltr' },
    kn: { name: 'Kannada', dir: 'ltr' }
}

const TRANSLATIONS = {
    en: {
        loading: 'Loading...',
        saved: 'Saved',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        submit: 'Submit',
        errorRequired: 'This field is required',
        navDashboard: 'Dashboard',
        navInventory: 'Inventory',
        navSettings: 'Settings',
        navBusinessSetup: 'Business Setup',
        activeBusiness: 'Active Business',
        setupTitle: 'Set Up Your Business',
        setupSubtitle: 'Tell us a bit about your business to get started.',
        businessName: 'Business Name',
        businessType: 'Business Type',
        whatsappNumber: 'WhatsApp Number',
        language: 'Language',
        description: 'Description',
        dashboardTitle: 'Dashboard',
        dashboardSubtitle: 'Overview for',
        whatsappActivation: 'WhatsApp Activation',
        botActive: 'Active ✅',
        botPending: 'Pending Activation ⏳',
        botSetupMessage: 'We are setting up your WhatsApp Business account. This usually takes 24-48 hours. We will notify you on',
        botLiveMessage: 'Your bot is live! Share your number',
        recentOrders: 'Recent Orders',
        noOrders: 'No Orders Yet',
        ordersEmptyMsg: 'Orders from WhatsApp customers will appear here.',
        inventoryTitle: 'Inventory',
        inventorySubtitle: 'Manage products for',
        categories: 'Categories',
        allProducts: 'All Products',
        addProduct: 'Add Product',
        editProduct: 'Edit Product',
        productName: 'Product Name',
        price: 'Price',
        category: 'Category',
        uploadImages: 'Upload Images',
        clickToUpload: 'Click to upload',
        settingsTitle: 'Settings',
        settingsSubtitle: 'Configure your WhatsApp bot for',
        botTone: 'Bot Tone',
        greeting: 'Greeting',
        autoGreet: 'Auto-greet new customers',
        businessHours: 'Business Hours',
        opens: 'Opens',
        closes: 'Closes',
        featureWishlist: 'Feature Wishlist',
        saveChanges: 'Save Changes'
    },
    hi: {
        loading: 'लोड हो रहा है...',
        saved: 'सहेज लिया',
        save: 'सहेजें',
        cancel: 'रद्द करें',
        delete: 'हटाएं',
        edit: 'संपादित करें',
        submit: 'जमा करें',
        errorRequired: 'यह फ़ील्ड आवश्यक है',
        navDashboard: 'डैशबोर्ड',
        navInventory: 'इन्वेंटरी',
        navSettings: 'सेटिंग्स',
        navBusinessSetup: 'व्यवसाय सेटअप',
        activeBusiness: 'सक्रिय व्यवसाय',
        setupTitle: 'अपना व्यवसाय सेटअप करें',
        setupSubtitle: 'शुरू करने के लिए हमें अपने व्यवसाय के बारे में थोड़ा बताएं।',
        businessName: 'व्यवसाय का नाम',
        businessType: 'व्यवसाय का प्रकार',
        whatsappNumber: 'व्हाट्सएप नंबर',
        language: 'भाषा',
        description: 'विवरण',
        dashboardTitle: 'डैशबोर्ड',
        dashboardSubtitle: 'का अवलोकन',
        whatsappActivation: 'व्हाट्सएप सक्रियण',
        botActive: 'सक्रिय ✅',
        botPending: 'सक्रियण लंबित ⏳',
        botSetupMessage: 'हम आपका व्हाट्सएप बिजनेस खाता सेटअप कर रहे हैं। इसमें आमतौर पर 24-48 घंटे लगते हैं। हम आपको सूचित करेंगे',
        botLiveMessage: 'आपका बॉट लाइव है! अपना नंबर साझा करें',
        recentOrders: 'हाल के ऑर्डर',
        noOrders: 'अभी तक कोई ऑर्डर नहीं',
        ordersEmptyMsg: 'व्हाट्सएप ग्राहकों के ऑर्डर यहां दिखाई देंगे।',
        inventoryTitle: 'इन्वेंटरी',
        inventorySubtitle: 'के लिए उत्पाद प्रबंधित करें',
        categories: 'श्रेणियाँ',
        allProducts: 'सभी उत्पाद',
        addProduct: 'उत्पाद जोड़ें',
        editProduct: 'उत्पाद संपादित करें',
        productName: 'उत्पाद का नाम',
        price: 'कीमत',
        category: 'श्रेणी',
        uploadImages: 'छवियां अपलोड करें',
        clickToUpload: 'अपलोड करने के लिए क्लिक करें',
        settingsTitle: 'सेटिंग्स',
        settingsSubtitle: 'के लिए अपना व्हाट्सएप बॉट कॉन्फ़िगर करें',
        botTone: 'बॉट का लहज़ा',
        greeting: 'अभिवादन',
        autoGreet: 'नए ग्राहकों का स्वतः स्वागत करें',
        businessHours: 'काम के घंटे',
        opens: 'खुलता है',
        closes: 'बंद होता है',
        featureWishlist: 'सुविधा विशलिस्ट',
        saveChanges: 'परिवर्तन सहेजें'
    },
    pa: {
        loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
        saved: 'ਸੇਵ ਕੀਤਾ',
        save: 'ਸੇਵ ਕਰੋ',
        cancel: 'ਰੱਦ ਕਰੋ',
        delete: 'ਹਟਾਓ',
        edit: 'ਸੋਧੋ',
        submit: 'ਜਮ੍ਹਾਂ ਕਰੋ',
        errorRequired: 'ਇਹ ਖੇਤਰ ਲਾਜ਼ਮੀ ਹੈ',
        navDashboard: 'ਡੈਸ਼ਬੋਰਡ',
        navInventory: 'ਇਨਵੈਂਟਰੀ',
        navSettings: 'ਸੈਟਿੰਗਾਂ',
        navBusinessSetup: 'ਕਾਰੋਬਾਰ ਸੈੱਟਅੱਪ',
        activeBusiness: 'ਸਰਗਰਮ ਕਾਰੋਬਾਰ',
        setupTitle: 'ਆਪਣਾ ਕਾਰੋਬਾਰ ਸੈੱਟਅੱਪ ਕਰੋ',
        setupSubtitle: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਸਾਨੂੰ ਆਪਣੇ ਕਾਰੋਬਾਰ ਬਾਰੇ ਥੋੜ੍ਹਾ ਦੱਸੋ।',
        businessName: 'ਕਾਰੋਬਾਰ ਦਾ ਨਾਮ',
        businessType: 'ਕਾਰੋਬਾਰ ਦੀ ਕਿਸਮ',
        whatsappNumber: 'ਵਟਸਐਪ ਨੰਬਰ',
        language: 'ਭਾਸ਼ਾ',
        description: 'ਵੇਰਵਾ',
        dashboardTitle: 'ਡੈਸ਼ਬੋਰਡ',
        dashboardSubtitle: 'ਦਾ ਸੰਖੇਪ ਜਾਣਕਾਰੀ',
        whatsappActivation: 'ਵਟਸਐਪ ਐਕਟੀਵੇਸ਼ਨ',
        botActive: 'ਸਰਗਰਮ ✅',
        botPending: 'ਐਕਟੀਵੇਸ਼ਨ ਬਾਕੀ ⏳',
        botSetupMessage: 'ਅਸੀਂ ਤੁਹਾਡਾ ਵਟਸਐਪ ਬਿਜ਼ਨਸ ਖਾਤਾ ਸੈੱਟਅੱਪ ਕਰ ਰਹੇ ਹਾਂ। ਇਸ ਵਿੱਚ ਆਮ ਤੌਰ ਤੇ 24-48 ਘੰਟੇ ਲੱਗਦੇ ਹਨ। ਅਸੀਂ ਤੁਹਾਨੂੰ ਸੂਚਿਤ ਕਰਾਂਗੇ',
        botLiveMessage: 'ਤੁਹਾਡਾ ਬੋਟ ਲਾਈਵ ਹੈ! ਆਪਣਾ ਨੰਬਰ ਸਾਂਝਾ ਕਰੋ',
        recentOrders: 'ਹਾਲੀਆ ਆਰਡਰ',
        noOrders: 'ਅਜੇ ਕੋਈ ਆਰਡਰ ਨਹੀਂ',
        ordersEmptyMsg: 'ਵਟਸਐਪ ਗਾਹਕਾਂ ਦੇ ਆਰਡਰ ਇੱਥੇ ਦਿਖਾਈ ਦੇਣਗੇ।',
        inventoryTitle: 'ਇਨਵੈਂਟਰੀ',
        inventorySubtitle: 'ਲਈ ਉਤਪਾਦ ਪ੍ਰਬੰਧਿਤ ਕਰੋ',
        categories: 'ਸ਼੍ਰੇਣੀਆਂ',
        allProducts: 'ਸਾਰੇ ਉਤਪਾਦ',
        addProduct: 'ਉਤਪਾਦ ਸ਼ਾਮਲ ਕਰੋ',
        editProduct: 'ਉਤਪਾਦ ਸੋਧੋ',
        productName: 'ਉਤਪਾਦ ਦਾ ਨਾਮ',
        price: 'ਕੀਮਤ',
        category: 'ਸ਼੍ਰੇਣੀ',
        uploadImages: 'ਤਸਵੀਰਾਂ ਅੱਪਲੋਡ ਕਰੋ',
        clickToUpload: 'ਅੱਪਲੋਡ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ',
        settingsTitle: 'ਸੈਟਿੰਗਾਂ',
        settingsSubtitle: 'ਲਈ ਆਪਣੇ ਵਟਸਐਪ ਬੋਟ ਨੂੰ ਕਨਫਿਗਰ ਕਰੋ',
        botTone: 'ਬੋਟ ਦਾ ਲਹਿਜ਼ਾ',
        greeting: 'ਸ਼ੁਭਕਾਮਨਾਵਾਂ',
        autoGreet: 'ਨਵੇਂ ਗਾਹਕਾਂ ਦਾ ਸਵੈ-ਸਵਾਗਤ',
        businessHours: 'ਕੰਮ ਦੇ ਘੰਟੇ',
        opens: 'ਖੁੱਲ੍ਹਦਾ ਹੈ',
        closes: 'ਬੰਦ ਹੁੰਦਾ ਹੈ',
        featureWishlist: 'ਫੀਚਰ ਵਿਸ਼ਲਿਸਟ',
        saveChanges: 'ਬਦਲਾਅ ਸੇਵ ਕਰੋ'
    },
    kn: {
        loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
        saved: 'ಉಳಿಸಲಾಗಿದೆ',
        save: 'ಉಳಿಸಿ',
        cancel: 'ರದ್ದುಮಾಡಿ',
        delete: 'ಅಳಿಸಿ',
        edit: 'ತಿದ್ದುಪಡಿ',
        submit: 'ಸಲ್ಲಿಸಿ',
        errorRequired: 'ಈ ಕ್ಷೇತ್ರವನ್ನು ಭರ್ತಿ ಮಾಡುವುದು ಕಡ್ಡಾಯ',
        navDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        navInventory: 'ಇನ್ವೆಂಟರಿ',
        navSettings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
        navBusinessSetup: 'ವ್ಯವಹಾರ ಸೆಟಪ್',
        activeBusiness: 'ಸಕ್ರಿಯ ವ್ಯವಹಾರ',
        setupTitle: 'ನಿಮ್ಮ ವ್ಯವಹಾರವನ್ನು ಹೊಂದಿಸಿ',
        setupSubtitle: 'ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ವ್ಯವಹಾರದ ಬಗ್ಗೆ ನಮಗೆ ಸ್ವಲ್ಪ ತಿಳಿಸಿ.',
        businessName: 'ವ್ಯವಹಾರದ ಹೆಸರು',
        businessType: 'ವ್ಯವಹಾರದ ಪ್ರಕಾರ',
        whatsappNumber: 'ವಾಟ್ಸಾಪ್ ಸಂಖ್ಯೆ',
        language: 'ಭಾಷೆ',
        description: 'ವಿವರಣೆ',
        dashboardTitle: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        dashboardSubtitle: 'ಇದರ ಅವಲೋಕನ',
        whatsappActivation: 'ವಾಟ್ಸಾಪ್ ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ',
        botActive: 'ಸಕ್ರಿಯ ✅',
        botPending: 'ಸಕ್ರಿಯಗೊಳಿಸುವಿಕೆ ಬಾಕಿ ಇದೆ ⏳',
        botSetupMessage: 'ನಿಮ್ಮ ವಾಟ್ಸಾಪ್ ಬಿಸಿನೆಸ್ ಖಾತೆಯನ್ನು ನಾವು ಹೊಂದಿಸುತ್ತಿದ್ದೇವೆ. ಇದಕ್ಕೆ ಸಾಮಾನ್ಯವಾಗಿ 24-48 ಗಂಟೆಗಳು ಬೇಕಾಗುತ್ತದೆ. ನಾವು ನಿಮಗೆ ತಿಳಿಸುತ್ತೇವೆ',
        botLiveMessage: 'ನಿಮ್ಮ ಬಾಟ್ ಲೈವ್ ಆಗಿದೆ! ನಿಮ್ಮ ಸಂಖ್ಯೆಯನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
        recentOrders: 'ಇತ್ತೀಚಿನ ಆದೇಶಗಳು',
        noOrders: 'ಇನ್ನೂ ಯಾವುದೇ ಆದೇಶಗಳಿಲ್ಲ',
        ordersEmptyMsg: 'ವಾಟ್ಸಾಪ್ ಗ್ರಾಹಕರ ಆದೇಶಗಳು ಇಲ್ಲಿ ಗೋಚರಿಸುತ್ತವೆ.',
        inventoryTitle: 'ಇನ್ವೆಂಟರಿ',
        inventorySubtitle: 'ಇದಕ್ಕಾಗಿ ಉತ್ಪನ್ನಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
        categories: 'ವರ್ಗಗಳು',
        allProducts: 'ಎಲ್ಲಾ ಉತ್ಪನ್ನಗಳು',
        addProduct: 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
        editProduct: 'ಉತ್ಪನ್ನ ತಿದ್ದುಪಡಿ',
        productName: 'ಉತ್ಪನ್ನದ ಹೆಸರು',
        price: 'ಬೆಲೆ',
        category: 'ವರ್ಗ',
        uploadImages: 'ಚಿತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
        clickToUpload: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
        settingsTitle: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
        settingsSubtitle: 'ಇದಕ್ಕಾಗಿ ನಿಮ್ಮ ವಾಟ್ಸಾಪ್ ಬಾಟ್ ಅನ್ನು ಕಾನ್ಫಿಗರ್ ಮಾಡಿ',
        botTone: 'ಬಾಟ್ ಧ್ವನಿ',
        greeting: 'ಶುಭಾಶಯ',
        autoGreet: 'ಹೊಸ ಗ್ರಾಹಕರನ್ನು ಸ್ವಯಂ ಸ್ವಾಗತಿಸಿ',
        businessHours: 'ವ್ಯವಹಾರದ ಸಮಯ',
        opens: 'ತೆರೆಯುತ್ತದೆ',
        closes: 'ಮುಚ್ಚುತ್ತದೆ',
        featureWishlist: 'ವೈಶಿಷ್ಟ್ಯ ಬಯಕೆಪಟ್ಟಿ',
        saveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ'
    }
}

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState('en')

    const t = (key) => {
        return TRANSLATIONS[language][key] || TRANSLATIONS['en'][key] || key
    }

    const value = {
        language,
        setLanguage,
        t,
        LANGUAGES
    }

    return (
        <LanguageContext.Provider value={value}>
            <div dir={LANGUAGES[language].dir}>
                {children}
            </div>
        </LanguageContext.Provider>
    )
}
